"""adiciona campo terceiro em lancamentos_fatura

Revision ID: 0cc484b7b642
Revises: 797a70478497
Create Date: 2026-07-12 19:19:36.472469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc484b7b642'
down_revision: Union[str, None] = '797a70478497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Registros já existentes: nenhum lançamento antigo é retroativamente
    # "de terceiro" até o usuário marcar isso manualmente — default False
    # pra todos os já gravados (ver CLAUDE.md "Compatibilidade com dados
    # existentes").
    with op.batch_alter_table('lancamentos_fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terceiro', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_fatura', schema=None) as batch_op:
        batch_op.drop_column('terceiro')

    # ### end Alembic commands ###
