"""schema inicial

Revision ID: 797a70478497
Revises: 
Create Date: 2026-07-03 22:05:21.362547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797a70478497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUTO', 'GASTO', name='tipocategoria', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'tipo', name='uq_categoria_nome_tipo')
    )
    op.create_table('config_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_fechamento_fatura', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumos_mensais',
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('nota_resumo', sa.Text(), nullable=True),
    sa.Column('congelado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('mes_referencia')
    )
    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_bruto', sa.String(length=150), nullable=False),
    sa.Column('nome_amigavel', sa.String(length=120), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('categoria_gasto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_gasto_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_bruto')
    )
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estabelecimentos_cnpj'), ['cnpj'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=20), nullable=True),
    sa.Column('nome_amigavel', sa.String(length=120), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=120), nullable=False),
    sa.Column('quantidade_normalizada', sa.Float(), nullable=False),
    sa.Column('unidade_normalizada', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_codigo_barras'), ['codigo_barras'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_nome_normalizado'), ['nome_normalizado'], unique=False)

    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('descricao_bruta', sa.String(length=120), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('origem', sa.Enum('NFCE', 'PRINT', 'PDF', name='origemcompra', native_enum=False), nullable=False),
    sa.Column('nfce_chave_acesso', sa.String(length=44), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compras_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_compras_nfce_chave_acesso'), ['nfce_chave_acesso'], unique=False)

    op.create_table('eventos_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_consumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_consumo_produto_id'), ['produto_id'], unique=False)

    op.create_table('itens_lista_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'COMPRADO', name='statusitemlista', native_enum=False), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    op.create_table('lancamentos_fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao_bruta', sa.String(length=150), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=True),
    sa.Column('categoria_gasto_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('origem', sa.Enum('NFCE', 'PRINT', 'PDF', name='origemcompra', native_enum=False), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('CREDITO', 'REFEICAO', name='formapagamento', native_enum=False), nullable=False),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('grupo_parcelamento', sa.String(length=36), nullable=True),
    sa.Column('mes_termino', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['categoria_gasto_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos_fatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_fatura_grupo_parcelamento'), ['grupo_parcelamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_fatura_mes_referencia'), ['mes_referencia'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_fatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_fatura_mes_referencia'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_fatura_grupo_parcelamento'))

    op.drop_table('lancamentos_fatura')
    op.drop_table('itens_lista_compra')
    with op.batch_alter_table('eventos_consumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_consumo_produto_id'))

    op.drop_table('eventos_consumo')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compras_nfce_chave_acesso'))
        batch_op.drop_index(batch_op.f('ix_compras_data'))

    op.drop_table('compras')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo_barras'))

    op.drop_table('produtos')
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estabelecimentos_cnpj'))

    op.drop_table('estabelecimentos')
    op.drop_table('resumos_mensais')
    op.drop_table('config_sistema')
    op.drop_table('categorias')
    # ### end Alembic commands ###
